# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Jekyll Windows'
tagline:          'A Windows theme for Jekyll'
description:      'A Sample blog using Jekyll Windows'
url:              'http://roachhd.github.io/JekyllMetro/'
baseurl:          'http://roachhd.github.io/JekyllMetro/'

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Katie Ball'
linkedin:       'https://linkedin.com//'
twitter:        'https://twitter.com/mektball'
facebook:       'https://www.facebook.com/roachhd'
gplus:          'https://plus.google.com/
/'

# Google Analytics
gahandler: 'UA-GOOGLES-1'

# Disqus
disqushandler: 'roachhd'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
